# Evolved from https://www.kaliber5.de/en/blog/preview-deployments_en
---
name: UI CD

on:
  push:
    branches:
      - main
      - 'ui-**'
  workflow_dispatch: {}
  
jobs:
  staging:
    name: Deploy to staging
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup node v16
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        uses: borales/actions-yarn@v4
        with:
          cmd: install
          dir: 'frontend'

  deploy:
    name: Actual deploy
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop'
    steps:
      - name: Deploy to staging
        run: |
          cd frontend
          yarn deploy:staging
        env:
          FF_BETACODE: ${{ secrets.FF_BETACODE }}
          AWS_KEY: ${{ secrets.DEPLOY_UI_AWS_KEY }}
          AWS_SECRET: ${{ secrets.DEPLOY_UI_SSH_KEY }}
          AWS_REGION: "us-east-1"
          STAGING_BUCKET: "staging.myfunforecast"
