# Evolved from https://www.kaliber5.de/en/blog/preview-deployments_en
---
name: Preview UI

on:
  push:
    branches:
      - main
      - 'ui/**'
  workflow_dispatch: {}
  
jobs:
  staging:
    name: Deploy to staging
    runs-on: ubuntu-latest
    if: ${{ github.event.label.name == 'ui' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup node v16
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        uses: borales/actions-yarn@v4
        with:
          cmd: install
          dir: 'frontend'

      - name: Deploy to staging
        run: |
          cd frontend
          yarn deploy:staging
        env:
          FF_BETACODE: ${{ secrets.FF_BETACODE_STAGING }}
          AWS_KEY: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "us-east-1"
          STAGING_BUCKET: "staging.myfunforecast"

